@startuml
'https://plantuml.com/class-diagram

class Main {
public static void main (String[] args)
}
package config {
class SessionConfig{

}
class ThemyleafConfig{

}

}
package controllers {
class AdminController{

}
class UserController{

}
class PaymentController{

}
class ShoppingCartController{

}

}

package entities {
class ShoppingCart{

}
class Cupcake{

}
class User{

}

}
package persistance {
class AdminMapper{
}
class ConnectionPool{

}
class UserMapper{

}
class PaymentMapper{
}
}
package exception {
class DatabaseException{

}

}




@enduml